[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
yew = { version = "0.20", features = ["csr"] }
wasm-logger = "0.2"
log = "0.4"
wasm-bindgen = "0.2"

yew-consent = { path = ".." }
